# Generated by Django 5.0.4 on 2024-04-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='permanent_address',
            field=models.IntegerField(max_length=100),
        ),
    ]
